sudo: false
language: node_js
node_js:
  - '10'

before_script:
  - bash -c "if [ -f client_secret.json ]; then echo 'client_secret exists.'; else echo ${GOOGLE_API} > client_secret.json; fi"
  - bash -c "echo "" >> client_secret.json"
  - mkdir ${CREDENTIALS_PATH
  - bash -c "if [ -f ${CREDENTIALS_PATH} ]; then echo 'credentials path exists.'; else echo ${GOOGLE_CREDENTIALS} > ${CREDENTIALS_PATH}; fi"
  - bash -c "echo "" >> ${CREDENTIALS_PATH}"
